export interface BranchOffice {
  name: string;
}

export interface PostalDivision {
  name: string;
  branchOffices: BranchOffice[];
}

export const MP_POSTAL_DIVISIONS: PostalDivision[] = [
  {
    name: "Bhopal Division",
    branchOffices: [
      { name: "Berasia BO" },
      { name: "Budhni BO" },
      { name: "Ichhawar BO" },
      { name: "Nasrullaganj BO" },
      { name: "Sehore BO" },
      { name: "Ashta BO" },
      { name: "Raisen BO" },
      { name: "Mandideep BO" },
      { name: "Obedullahganj BO" },
      { name: "Silwani BO" },
      { name: "Vidisha BO" },
      { name: "Ganjbasoda BO" },
      { name: "Begumganj BO" },
      { name: "Basoda BO" },
      { name: "Kurwai BO" },
      { name: "Sironj BO" },
      { name: "Sanchi BO" },
    ],
  },
  {
    name: "Indore Division",
    branchOffices: [
      { name: "Dewas BO" },
      { name: "Hatod BO" },
      { name: "Sanwer BO" },
      { name: "Mhow BO" },
      { name: "Pithampur BO" },
      { name: "Mahow Cantonment BO" },
      { name: "Khategaon BO" },
      { name: "Kannod BO" },
      { name: "Timarni BO" },
      { name: "Bagli BO" },
      { name: "Harda BO" },
      { name: "Khirkiya BO" },
      { name: "Hansua BO" },
      { name: "Sirali BO" },
      { name: "Rajgarh BO" },
    ],
  },
  {
    name: "Jabalpur Division",
    branchOffices: [
      { name: "Sihora BO" },
      { name: "Katangi BO" },
      { name: "Patan BO" },
      { name: "Majholi BO" },
      { name: "Shahpura BO" },
      { name: "Bargi BO" },
      { name: "Panagar BO" },
      { name: "Bhedaghat BO" },
      { name: "Kundam BO" },
      { name: "Madan Mahal BO" },
      { name: "Lamti BO" },
      { name: "Barela BO" },
      { name: "Dundi BO" },
      { name: "Tewar BO" },
      { name: "Khamaria BO" },
      { name: "Adhartal BO" },
      { name: "Tilwara Ghat BO" },
    ],
  },
  {
    name: "Chhindwara Division",
    branchOffices: [
      { name: "Parasia BO" },
      { name: "Sausar BO" },
      { name: "Pandhurna BO" },
      { name: "Amarwara BO" },
      { name: "Tamia BO" },
      { name: "Harrai BO" },
      { name: "Chaurai BO" },
      { name: "Mohkhed BO" },
      { name: "Umranala BO" },
      { name: "Bisapur BO" },
      { name: "Jamai BO" },
      { name: "Chand BO" },
      { name: "Betul BO" },
      { name: "Multai BO" },
      { name: "Athner BO" },
      { name: "Amla BO" },
      { name: "Bhainsdehi BO" },
      { name: "Shahpur BO" },
    ],
  },
  {
    name: "Gwalior Division",
    branchOffices: [
      { name: "Dabra BO" },
      { name: "Bhitarwar BO" },
      { name: "Pichhore BO" },
      { name: "Shivpuri BO" },
      { name: "Kolaras BO" },
      { name: "Karera BO" },
      { name: "Pohri BO" },
      { name: "Datia BO" },
      { name: "Bhander BO" },
      { name: "Sewda BO" },
      { name: "Gwalior Cantonment BO" },
      { name: "Morar BO" },
      { name: "Lashkar BO" },
      { name: "Maharajpur BO" },
    ],
  },
  {
    name: "Sagar Division",
    branchOffices: [
      { name: "Banda BO" },
      { name: "Khurai BO" },
      { name: "Bina BO" },
      { name: "Rehli BO" },
      { name: "Rahatgarh BO" },
      { name: "Deori BO" },
      { name: "Garhakota BO" },
      { name: "Tikamgarh BO" },
      { name: "Baldeogarh BO" },
      { name: "Jatara BO" },
      { name: "Palera BO" },
      { name: "Niwari BO" },
      { name: "Prithvipur BO" },
      { name: "Chhatarpur BO" },
      { name: "Bijawar BO" },
      { name: "Buxwaha BO" },
      { name: "Nowgong BO" },
      { name: "Badamalhera BO" },
    ],
  },
  {
    name: "Rewa Division",
    branchOffices: [
      { name: "Mauganj BO" },
      { name: "Hanumana BO" },
      { name: "Naigarhi BO" },
      { name: "Teonthar BO" },
      { name: "Mangawan BO" },
      { name: "Jawa BO" },
      { name: "Sirmaur BO" },
      { name: "Rampur Naikin BO" },
      { name: "Sirmour BO" },
      { name: "Satna BO" },
      { name: "Maihar BO" },
      { name: "Nagod BO" },
      { name: "Unchehara BO" },
      { name: "Amarpatan BO" },
      { name: "Rampur Baghelan BO" },
      { name: "Raipur Karchuliyan BO" },
    ],
  },
  {
    name: "Ujjain Division",
    branchOffices: [
      { name: "Mahidpur BO" },
      { name: "Tarana BO" },
      { name: "Khachrod BO" },
      { name: "Nagda BO" },
      { name: "Barnagar BO" },
      { name: "Badnagar BO" },
      { name: "Ghattia BO" },
      { name: "Manasa BO" },
      { name: "Jawad BO" },
      { name: "Mandsaur BO" },
      { name: "Daloda BO" },
      { name: "Neemuch BO" },
      { name: "Garoth BO" },
      { name: "Sitamau BO" },
      { name: "Suwasra BO" },
    ],
  },
  {
    name: "Satna Division",
    branchOffices: [
      { name: "Maihar BO" },
      { name: "Rampur Baghelan BO" },
      { name: "Unchehara BO" },
      { name: "Amarpatan BO" },
      { name: "Nagod BO" },
      { name: "Ramnagar BO" },
      { name: "Birsinghpur BO" },
      { name: "Kotar BO" },
      { name: "Jaso BO" },
      { name: "Satna City BO" },
      { name: "Rewa Road BO" },
      { name: "Birsinghpur Pali BO" },
    ],
  },
  {
    name: "Hoshangabad Division",
    branchOffices: [
      { name: "Pipariya BO" },
      { name: "Sohagpur BO" },
      { name: "Seoni Malwa BO" },
      { name: "Itarsi BO" },
      { name: "Bankhedi BO" },
      { name: "Babai BO" },
      { name: "Pachmarhi BO" },
      { name: "Kesla BO" },
      { name: "Mateena BO" },
      { name: "Tawa BO" },
    ],
  },
  {
    name: "Morena Division",
    branchOffices: [
      { name: "Ambah BO" },
      { name: "Porsa BO" },
      { name: "Sabalgarh BO" },
      { name: "Sheopur BO" },
      { name: "Vijaypur BO" },
      { name: "Kailaras BO" },
      { name: "Joura BO" },
      { name: "Sumaoli BO" },
      { name: "Pahargarh BO" },
      { name: "Jaura BO" },
    ],
  },
  {
    name: "Sehore Division",
    branchOffices: [
      { name: "Ashta BO" },
      { name: "Nasrullaganj BO" },
      { name: "Budhni BO" },
      { name: "Rehti BO" },
      { name: "Doraha BO" },
      { name: "Banskhedi BO" },
      { name: "Ichhawar BO" },
    ],
  },
  {
    name: "Shahdol Division",
    branchOffices: [
      { name: "Anuppur BO" },
      { name: "Jaithari BO" },
      { name: "Pushprajgarh BO" },
      { name: "Beohari BO" },
      { name: "Umaria BO" },
      { name: "Chandia BO" },
      { name: "Sohagpur BO" },
      { name: "Birsinghpur BO" },
      { name: "Pali BO" },
      { name: "Kotma BO" },
      { name: "Amarkantak BO" },
    ],
  },
  {
    name: "Damoh Division",
    branchOffices: [
      { name: "Hatta BO" },
      { name: "Patera BO" },
      { name: "Jabera BO" },
      { name: "Batiyagarh BO" },
      { name: "Patharia BO" },
      { name: "Tendukheda BO" },
      { name: "Hindoria BO" },
    ],
  },
  {
    name: "Narsinghpur Division",
    branchOffices: [
      { name: "Gadarwara BO" },
      { name: "Kareli BO" },
      { name: "Saikheda BO" },
      { name: "Gotegaon BO" },
      { name: "Chhapara BO" },
      { name: "Chichali BO" },
      { name: "Nainpur BO" },
      { name: "Mandla BO" },
      { name: "Bichhia BO" },
      { name: "Niwas BO" },
      { name: "Ghughari BO" },
      { name: "Dindori BO" },
      { name: "Shahpura BO" },
    ],
  },
  {
    name: "Khandwa Division",
    branchOffices: [
      { name: "Pandhana BO" },
      { name: "Khalwa BO" },
      { name: "Punasa BO" },
      { name: "Mandhata BO" },
      { name: "Khargone BO" },
      { name: "Kasrawad BO" },
      { name: "Bhikangaon BO" },
      { name: "Maheshwar BO" },
      { name: "Mandleshwar BO" },
      { name: "Barwaha BO" },
      { name: "Badwani BO" },
      { name: "Pati BO" },
      { name: "Sendhwa BO" },
      { name: "Rajpur BO" },
      { name: "Pansemal BO" },
      { name: "Kukshi BO" },
    ],
  },
  {
    name: "Ratlam Division",
    branchOffices: [
      { name: "Sailana BO" },
      { name: "Jaora BO" },
      { name: "Piploda BO" },
      { name: "Alot BO" },
      { name: "Tal BO" },
      { name: "Wari BO" },
      { name: "Namli BO" },
      { name: "Bajna BO" },
      { name: "Mhow Neemuch Road BO" },
    ],
  },
  {
    name: "Guna Division",
    branchOffices: [
      { name: "Raghogarh BO" },
      { name: "Chachoda BO" },
      { name: "Aron BO" },
      { name: "Ashoknagar BO" },
      { name: "Mungaoli BO" },
      { name: "Chanderi BO" },
      { name: "Isagarh BO" },
      { name: "Pichhore BO" },
    ],
  },
  {
    name: "Bhind Division",
    branchOffices: [
      { name: "Lahar BO" },
      { name: "Mehgaon BO" },
      { name: "Ater BO" },
      { name: "Mihona BO" },
      { name: "Gohad BO" },
      { name: "Gormi BO" },
      { name: "Raon BO" },
    ],
  },
  {
    name: "Seoni Division",
    branchOffices: [
      { name: "Lakhnadon BO" },
      { name: "Barghat BO" },
      { name: "Ghansaur BO" },
      { name: "Chhapara BO" },
      { name: "Keolari BO" },
      { name: "Khurai BO" },
      { name: "Bandol BO" },
    ],
  },
  {
    name: "Balaghat Division",
    branchOffices: [
      { name: "Baihar BO" },
      { name: "Katangi BO" },
      { name: "Kirnapur BO" },
      { name: "Lalburra BO" },
      { name: "Paraswada BO" },
      { name: "Khairlanji BO" },
      { name: "Waraseoni BO" },
      { name: "Khairagarh BO" },
    ],
  },
  {
    name: "Shivpuri Division",
    branchOffices: [
      { name: "Pichhore BO" },
      { name: "Kolaras BO" },
      { name: "Karera BO" },
      { name: "Pohri BO" },
      { name: "Narwar BO" },
      { name: "Bairad BO" },
      { name: "Khaniyadhana BO" },
    ],
  },
  {
    name: "Vidisha Division",
    branchOffices: [
      { name: "Ganjbasoda BO" },
      { name: "Sironj BO" },
      { name: "Kurwai BO" },
      { name: "Lateri BO" },
      { name: "Gyaraspur BO" },
      { name: "Sanchi BO" },
      { name: "Basoda BO" },
    ],
  },
  {
    name: "Tikamgarh Division",
    branchOffices: [
      { name: "Baldeogarh BO" },
      { name: "Jatara BO" },
      { name: "Palera BO" },
      { name: "Niwari BO" },
      { name: "Prithvipur BO" },
      { name: "Lidhora BO" },
    ],
  },
  {
    name: "Khargone Division",
    branchOffices: [
      { name: "Maheshwar BO" },
      { name: "Kasrawad BO" },
      { name: "Bhikangaon BO" },
      { name: "Mandleshwar BO" },
      { name: "Barwaha BO" },
      { name: "Badwani BO" },
      { name: "Gogawan BO" },
    ],
  },
  {
    name: "Panna Division",
    branchOffices: [
      { name: "Pawai BO" },
      { name: "Ajaigarh BO" },
      { name: "Shahnagar BO" },
      { name: "Devendra Nagar BO" },
      { name: "Gunnour BO" },
      { name: "Simaria BO" },
    ],
  },
  {
    name: "Sidhi Division",
    branchOffices: [
      { name: "Churhat BO" },
      { name: "Singrauli BO" },
      { name: "Waidhan BO" },
      { name: "Rampur Naikin BO" },
      { name: "Beohari BO" },
      { name: "Chitrangi BO" },
      { name: "Devsar BO" },
    ],
  },
  {
    name: "Mandla Division",
    branchOffices: [
      { name: "Bichhia BO" },
      { name: "Niwas BO" },
      { name: "Ghughari BO" },
      { name: "Mawai BO" },
      { name: "Narayanganj BO" },
      { name: "Kundi BO" },
    ],
  },
  {
    name: "Dhar Division",
    branchOffices: [
      { name: "Manawar BO" },
      { name: "Sardarpur BO" },
      { name: "Dharampuri BO" },
      { name: "Gandhwani BO" },
      { name: "Nalcha BO" },
      { name: "Tirla BO" },
      { name: "Kukshi BO" },
      { name: "Pitlad BO" },
    ],
  },
  {
    name: "Alirajpur Division",
    branchOffices: [
      { name: "Jobat BO" },
      { name: "Sondwa BO" },
      { name: "Udaigarh BO" },
      { name: "Katthiwada BO" },
      { name: "Bhabra BO" },
    ],
  },
  {
    name: "Jhabua Division",
    branchOffices: [
      { name: "Petlawad BO" },
      { name: "Meghnagar BO" },
      { name: "Ranapur BO" },
      { name: "Thandla BO" },
      { name: "Rama BO" },
    ],
  },
];
