/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicationId = IDL.Nat;
export const CandidateId = IDL.Nat;
export const AdminCandidateId = IDL.Nat;
export const DocumentType = IDL.Variant({
  'TenthCertificate' : IDL.Null,
  'Aadhaar' : IDL.Null,
  'TwelfthCertificate' : IDL.Null,
  'CharacterCertificate' : IDL.Null,
  'PanCard' : IDL.Null,
  'ComputerCertificate' : IDL.Null,
  'Photo' : IDL.Null,
  'AttestationForm' : IDL.Null,
  'Domicile' : IDL.Null,
  'MedicalCertificate' : IDL.Null,
  'CasteCertificate' : IDL.Null,
  'IncomeCertificate' : IDL.Null,
  'Signature' : IDL.Null,
  'RegistrationForm' : IDL.Null,
  'IdentityCertificate' : IDL.Null,
});
export const DocumentId = IDL.Nat;
export const Document = IDL.Record({
  'id' : DocumentId,
  'documentType' : DocumentType,
  'fileName' : IDL.Text,
  'registrationNo' : IDL.Text,
  'candidateId' : AdminCandidateId,
  'uploadedAt' : IDL.Int,
  'fileKey' : IDL.Text,
});
export const VacancyId = IDL.Nat;
export const Vacancy = IDL.Record({
  'id' : VacancyId,
  'postType' : IDL.Text,
  'branchOfficeName' : IDL.Text,
  'createdAt' : IDL.Int,
  'division' : IDL.Text,
  'circle' : IDL.Text,
  'basicPay' : IDL.Nat,
  'isActive' : IDL.Bool,
  'totalSeats' : IDL.Nat,
  'category' : IDL.Text,
  'filledSeats' : IDL.Nat,
});
export const Post = IDL.Record({
  'stPosts' : IDL.Nat,
  'scPosts' : IDL.Nat,
  'obcPosts' : IDL.Nat,
  'category' : IDL.Text,
  'totalPosts' : IDL.Nat,
  'urPosts' : IDL.Nat,
});
export const Division = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'posts' : IDL.Vec(Post),
});
export const CircleId = IDL.Nat;
export const NotifType = IDL.Variant({
  'important' : IDL.Null,
  'urgent' : IDL.Null,
  'general' : IDL.Null,
});
export const NotificationId = IDL.Nat;
export const UpdateCategory = IDL.Variant({
  'officialLetter' : IDL.Null,
  'recruitment' : IDL.Null,
  'tender' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const OfficialUpdate = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Timestamp,
  'createdBy' : IDL.Text,
  'isActive' : IDL.Bool,
  'pdfUrl' : IDL.Opt(IDL.Text),
  'category' : UpdateCategory,
  'isNew' : IDL.Bool,
});
export const UserId = IDL.Nat;
export const AdminCandidateStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Verified' : IDL.Null,
  'Pending' : IDL.Null,
});
export const SubjectMark = IDL.Record({
  'subject' : IDL.Text,
  'marksOrGrade' : IDL.Text,
});
export const PostPreference = IDL.Record({
  'postType' : IDL.Text,
  'preferenceNo' : IDL.Nat,
  'branchOfficeName' : IDL.Text,
  'basicPay' : IDL.Nat,
  'category' : IDL.Text,
});
export const FeeStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Paid' : IDL.Null,
  'Pending' : IDL.Null,
});
export const AddressInfo = IDL.Record({
  'street' : IDL.Text,
  'doorNo' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'village' : IDL.Text,
  'pincode' : IDL.Text,
});
export const ResultType = IDL.Variant({
  'CGPA' : IDL.Null,
  'Percentage' : IDL.Null,
  'GradePoint' : IDL.Null,
});
export const AdminCandidate = IDL.Record({
  'id' : AdminCandidateId,
  'ph' : IDL.Bool,
  'dob' : IDL.Text,
  'subjectMarks' : IDL.Vec(SubjectMark),
  'isEmployed' : IDL.Bool,
  'status' : AdminCandidateStatus,
  'divisionForVerification' : IDL.Text,
  'photoPath' : IDL.Text,
  'postPreferences' : IDL.Vec(PostPreference),
  'percentageObtained' : IDL.Text,
  'canRideBicycle' : IDL.Bool,
  'feeStatus' : FeeStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'rejectionReason' : IDL.Text,
  'division' : IDL.Text,
  'circle' : IDL.Text,
  'totalCgpa' : IDL.Text,
  'aadhaar' : IDL.Text,
  'declarationsAccepted' : IDL.Bool,
  'email' : IDL.Text,
  'permanentAddress' : AddressInfo,
  'updatedAt' : IDL.Int,
  'yearOfPassing' : IDL.Text,
  'signaturePath' : IDL.Text,
  'fatherName' : IDL.Text,
  'nocAvailable' : IDL.Bool,
  'gender' : IDL.Text,
  'totalGrade' : IDL.Text,
  'boardName' : IDL.Text,
  'category' : IDL.Text,
  'resultType' : ResultType,
  'mobile' : IDL.Text,
  'registrationNo' : IDL.Text,
  'stateOfBoard' : IDL.Text,
  'boardRemarks' : IDL.Text,
  'presentAddress' : AddressInfo,
  'applicationFormData' : IDL.Opt(IDL.Text),
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'notifType' : NotifType,
  'date' : Timestamp,
  'createdBy' : UserId,
  'isActive' : IDL.Bool,
});
export const ApplicationStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'underReview' : IDL.Null,
  'rejected' : IDL.Null,
  'shortlisted' : IDL.Null,
  'draft' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'success' : IDL.Null,
  'notRequired' : IDL.Null,
  'failed' : IDL.Null,
});
export const EducationDetails = IDL.Record({
  'totalMarks' : IDL.Nat,
  'marksObtained' : IDL.Nat,
  'yearOfPassing' : IDL.Text,
  'boardName' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const Preferences = IDL.Record({
  'postCategory' : IDL.Text,
  'division' : IDL.Text,
  'circle' : IDL.Text,
  'state' : IDL.Text,
});
export const Application = IDL.Record({
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'documentUrls' : IDL.Vec(IDL.Text),
  'paymentStatus' : PaymentStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'submittedAt' : IDL.Opt(Timestamp),
  'educationDetails' : EducationDetails,
  'preferences' : Preferences,
});
export const PaymentId = IDL.Nat;
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'netbanking' : IDL.Null,
  'card' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : PaymentId,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'applicationId' : ApplicationId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'applicant' : IDL.Null,
  'admin' : IDL.Null,
});
export const AddressType = IDL.Record({
  'street' : IDL.Text,
  'doorNo' : IDL.Text,
  'city' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'pincode' : IDL.Text,
});
export const User = IDL.Record({
  'id' : UserId,
  'dob' : IDL.Text,
  'principal' : IDL.Principal,
  'subcategory' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'photoUrl' : IDL.Opt(IDL.Text),
  'aadhaar' : IDL.Text,
  'email' : IDL.Text,
  'isVerified' : IDL.Bool,
  'signatureUrl' : IDL.Opt(IDL.Text),
  'address' : AddressType,
  'gender' : IDL.Text,
  'category' : IDL.Text,
  'mobile' : IDL.Text,
});
export const CandidateLoginResult = IDL.Record({
  'status' : AdminCandidateStatus,
  'token' : IDL.Text,
  'name' : IDL.Text,
  'mobile' : IDL.Text,
  'registrationNo' : IDL.Text,
});
export const ShortlistedCandidate = IDL.Record({
  'id' : CandidateId,
  'applicationId' : ApplicationId,
  'rank' : IDL.Nat,
  'division' : IDL.Text,
  'circle' : IDL.Text,
  'state' : IDL.Text,
  'rollNumber' : IDL.Text,
  'category' : IDL.Text,
  'candidateName' : IDL.Text,
});
export const Circle = IDL.Record({
  'id' : CircleId,
  'stateName' : IDL.Text,
  'divisions' : IDL.Vec(Division),
  'circleName' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpResponse = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  'addDocumentUrl' : IDL.Func([ApplicationId, IDL.Text], [], []),
  'adminAddCandidate' : IDL.Func(
      [
        ApplicationId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [CandidateId],
      [],
    ),
  'adminAddDocument' : IDL.Func(
      [AdminCandidateId, IDL.Text, DocumentType, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Document, 'err' : IDL.Text })],
      [],
    ),
  'adminAddVacancy' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : Vacancy, 'err' : IDL.Text })],
      [],
    ),
  'adminCreateCircle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(Division)],
      [CircleId],
      [],
    ),
  'adminCreateNotification' : IDL.Func(
      [IDL.Text, IDL.Text, NotifType],
      [NotificationId],
      [],
    ),
  'adminCreateOfficialUpdate' : IDL.Func(
      [IDL.Text, IDL.Text, UpdateCategory, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : OfficialUpdate, 'err' : IDL.Text })],
      [],
    ),
  'adminDeactivateNotification' : IDL.Func([NotificationId], [], []),
  'adminDeleteCandidate' : IDL.Func([CandidateId], [], []),
  'adminDeleteCircle' : IDL.Func([CircleId], [], []),
  'adminDeleteDocument' : IDL.Func(
      [DocumentId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteNotification' : IDL.Func([NotificationId], [], []),
  'adminDeleteOfficialUpdate' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteUser' : IDL.Func([UserId], [], []),
  'adminDeleteVacancy' : IDL.Func(
      [VacancyId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetActiveVacancies' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Vacancy)],
      ['query'],
    ),
  'adminGetAllCandidates' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(AdminCandidateStatus)],
      [IDL.Vec(AdminCandidate)],
      ['query'],
    ),
  'adminGetAllVacancies' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Vacancy)],
      ['query'],
    ),
  'adminGetCandidate' : IDL.Func(
      [AdminCandidateId],
      [IDL.Opt(AdminCandidate)],
      ['query'],
    ),
  'adminGetCandidatesByRegistrationNo' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AdminCandidate)],
      ['query'],
    ),
  'adminGetDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'pending' : IDL.Nat,
          'approved' : IDL.Nat,
          'rejected' : IDL.Nat,
          'totalCandidates' : IDL.Nat,
          'circleStats' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'divisionStats' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        }),
      ],
      ['query'],
    ),
  'adminGetDocuments' : IDL.Func(
      [AdminCandidateId],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'adminListAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], []),
  'adminListAllOfficialUpdates' : IDL.Func([], [IDL.Vec(OfficialUpdate)], []),
  'adminListApplications' : IDL.Func([], [IDL.Vec(Application)], []),
  'adminListApplicationsByStatus' : IDL.Func(
      [ApplicationStatus],
      [IDL.Vec(Application)],
      [],
    ),
  'adminListPayments' : IDL.Func([], [IDL.Vec(Payment)], []),
  'adminListUsers' : IDL.Func([], [IDL.Vec(User)], []),
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminRegisterCandidate' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        AddressInfo,
        AddressInfo,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ResultType,
        IDL.Vec(SubjectMark),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Vec(PostPreference),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : AdminCandidate, 'err' : IDL.Text })],
      [],
    ),
  'adminSetCandidateApplicationForm' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetUserRole' : IDL.Func([UserId, UserRole], [], []),
  'adminUpdateApplicationStatus' : IDL.Func(
      [ApplicationId, ApplicationStatus],
      [],
      [],
    ),
  'adminUpdateCandidateStatus' : IDL.Func(
      [AdminCandidateId, AdminCandidateStatus, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : AdminCandidate, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateCircle' : IDL.Func(
      [CircleId, IDL.Text, IDL.Text, IDL.Vec(Division)],
      [],
      [],
    ),
  'adminUpdateFeeStatus' : IDL.Func(
      [AdminCandidateId, FeeStatus],
      [IDL.Variant({ 'ok' : AdminCandidate, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateNotification' : IDL.Func(
      [NotificationId, IDL.Text, IDL.Text, NotifType],
      [],
      [],
    ),
  'adminUpdateOfficialUpdate' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Variant({ 'ok' : OfficialUpdate, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdatePaymentStatus' : IDL.Func([PaymentId, PaymentStatus], [], []),
  'adminUpdateVacancy' : IDL.Func(
      [VacancyId, IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : Vacancy, 'err' : IDL.Text })],
      [],
    ),
  'adminVerifyUser' : IDL.Func([UserId], [], []),
  'candidateLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : CandidateLoginResult, 'err' : IDL.Text })],
      [],
    ),
  'chatWithAI' : IDL.Func([IDL.Text], [IDL.Text], []),
  'confirmPayment' : IDL.Func([PaymentId, IDL.Text], [], []),
  'createApplication' : IDL.Func(
      [EducationDetails, Preferences],
      [ApplicationId],
      [],
    ),
  'getApplicationById' : IDL.Func(
      [ApplicationId],
      [IDL.Opt(Application)],
      ['query'],
    ),
  'getCandidateByEmail' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getCandidateById' : IDL.Func(
      [CandidateId],
      [IDL.Opt(ShortlistedCandidate)],
      ['query'],
    ),
  'getCandidateProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AdminCandidate)],
      ['query'],
    ),
  'getCircleById' : IDL.Func([CircleId], [IDL.Opt(Circle)], ['query']),
  'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getNotificationById' : IDL.Func(
      [NotificationId],
      [IDL.Opt(Notification)],
      ['query'],
    ),
  'getPaymentById' : IDL.Func([PaymentId], [IDL.Opt(Payment)], ['query']),
  'getUserById' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'httpTransform' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : HttpResponse,
        }),
      ],
      [HttpResponse],
      ['query'],
    ),
  'initiatePayment' : IDL.Func(
      [ApplicationId, IDL.Nat, PaymentMethod],
      [PaymentId],
      [],
    ),
  'listActiveNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'listActiveOfficialUpdates' : IDL.Func(
      [],
      [IDL.Vec(OfficialUpdate)],
      ['query'],
    ),
  'listAllCandidates' : IDL.Func(
      [],
      [IDL.Vec(ShortlistedCandidate)],
      ['query'],
    ),
  'listAllCircles' : IDL.Func([], [IDL.Vec(Circle)], ['query']),
  'listCandidatesByCircle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ShortlistedCandidate)],
      ['query'],
    ),
  'listCandidatesByState' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ShortlistedCandidate)],
      ['query'],
    ),
  'listCirclesByState' : IDL.Func([IDL.Text], [IDL.Vec(Circle)], ['query']),
  'listOfficialUpdatesByCategory' : IDL.Func(
      [UpdateCategory],
      [IDL.Vec(OfficialUpdate)],
      ['query'],
    ),
  'listStates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'registerUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        AddressType,
      ],
      [UserId],
      [],
    ),
  'requestOTP' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'submitApplication' : IDL.Func([ApplicationId], [], []),
  'updateApplication' : IDL.Func(
      [ApplicationId, EducationDetails, Preferences],
      [],
      [],
    ),
  'updatePhotoUrl' : IDL.Func([IDL.Text], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, AddressType],
      [],
      [],
    ),
  'updateSignatureUrl' : IDL.Func([IDL.Text], [], []),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicationId = IDL.Nat;
  const CandidateId = IDL.Nat;
  const AdminCandidateId = IDL.Nat;
  const DocumentType = IDL.Variant({
    'TenthCertificate' : IDL.Null,
    'Aadhaar' : IDL.Null,
    'TwelfthCertificate' : IDL.Null,
    'CharacterCertificate' : IDL.Null,
    'PanCard' : IDL.Null,
    'ComputerCertificate' : IDL.Null,
    'Photo' : IDL.Null,
    'AttestationForm' : IDL.Null,
    'Domicile' : IDL.Null,
    'MedicalCertificate' : IDL.Null,
    'CasteCertificate' : IDL.Null,
    'IncomeCertificate' : IDL.Null,
    'Signature' : IDL.Null,
    'RegistrationForm' : IDL.Null,
    'IdentityCertificate' : IDL.Null,
  });
  const DocumentId = IDL.Nat;
  const Document = IDL.Record({
    'id' : DocumentId,
    'documentType' : DocumentType,
    'fileName' : IDL.Text,
    'registrationNo' : IDL.Text,
    'candidateId' : AdminCandidateId,
    'uploadedAt' : IDL.Int,
    'fileKey' : IDL.Text,
  });
  const VacancyId = IDL.Nat;
  const Vacancy = IDL.Record({
    'id' : VacancyId,
    'postType' : IDL.Text,
    'branchOfficeName' : IDL.Text,
    'createdAt' : IDL.Int,
    'division' : IDL.Text,
    'circle' : IDL.Text,
    'basicPay' : IDL.Nat,
    'isActive' : IDL.Bool,
    'totalSeats' : IDL.Nat,
    'category' : IDL.Text,
    'filledSeats' : IDL.Nat,
  });
  const Post = IDL.Record({
    'stPosts' : IDL.Nat,
    'scPosts' : IDL.Nat,
    'obcPosts' : IDL.Nat,
    'category' : IDL.Text,
    'totalPosts' : IDL.Nat,
    'urPosts' : IDL.Nat,
  });
  const Division = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'posts' : IDL.Vec(Post),
  });
  const CircleId = IDL.Nat;
  const NotifType = IDL.Variant({
    'important' : IDL.Null,
    'urgent' : IDL.Null,
    'general' : IDL.Null,
  });
  const NotificationId = IDL.Nat;
  const UpdateCategory = IDL.Variant({
    'officialLetter' : IDL.Null,
    'recruitment' : IDL.Null,
    'tender' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const OfficialUpdate = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Timestamp,
    'createdBy' : IDL.Text,
    'isActive' : IDL.Bool,
    'pdfUrl' : IDL.Opt(IDL.Text),
    'category' : UpdateCategory,
    'isNew' : IDL.Bool,
  });
  const UserId = IDL.Nat;
  const AdminCandidateStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Verified' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const SubjectMark = IDL.Record({
    'subject' : IDL.Text,
    'marksOrGrade' : IDL.Text,
  });
  const PostPreference = IDL.Record({
    'postType' : IDL.Text,
    'preferenceNo' : IDL.Nat,
    'branchOfficeName' : IDL.Text,
    'basicPay' : IDL.Nat,
    'category' : IDL.Text,
  });
  const FeeStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Paid' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const AddressInfo = IDL.Record({
    'street' : IDL.Text,
    'doorNo' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'village' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const ResultType = IDL.Variant({
    'CGPA' : IDL.Null,
    'Percentage' : IDL.Null,
    'GradePoint' : IDL.Null,
  });
  const AdminCandidate = IDL.Record({
    'id' : AdminCandidateId,
    'ph' : IDL.Bool,
    'dob' : IDL.Text,
    'subjectMarks' : IDL.Vec(SubjectMark),
    'isEmployed' : IDL.Bool,
    'status' : AdminCandidateStatus,
    'divisionForVerification' : IDL.Text,
    'photoPath' : IDL.Text,
    'postPreferences' : IDL.Vec(PostPreference),
    'percentageObtained' : IDL.Text,
    'canRideBicycle' : IDL.Bool,
    'feeStatus' : FeeStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'rejectionReason' : IDL.Text,
    'division' : IDL.Text,
    'circle' : IDL.Text,
    'totalCgpa' : IDL.Text,
    'aadhaar' : IDL.Text,
    'declarationsAccepted' : IDL.Bool,
    'email' : IDL.Text,
    'permanentAddress' : AddressInfo,
    'updatedAt' : IDL.Int,
    'yearOfPassing' : IDL.Text,
    'signaturePath' : IDL.Text,
    'fatherName' : IDL.Text,
    'nocAvailable' : IDL.Bool,
    'gender' : IDL.Text,
    'totalGrade' : IDL.Text,
    'boardName' : IDL.Text,
    'category' : IDL.Text,
    'resultType' : ResultType,
    'mobile' : IDL.Text,
    'registrationNo' : IDL.Text,
    'stateOfBoard' : IDL.Text,
    'boardRemarks' : IDL.Text,
    'presentAddress' : AddressInfo,
    'applicationFormData' : IDL.Opt(IDL.Text),
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'notifType' : NotifType,
    'date' : Timestamp,
    'createdBy' : UserId,
    'isActive' : IDL.Bool,
  });
  const ApplicationStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'underReview' : IDL.Null,
    'rejected' : IDL.Null,
    'shortlisted' : IDL.Null,
    'draft' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'notRequired' : IDL.Null,
    'failed' : IDL.Null,
  });
  const EducationDetails = IDL.Record({
    'totalMarks' : IDL.Nat,
    'marksObtained' : IDL.Nat,
    'yearOfPassing' : IDL.Text,
    'boardName' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const Preferences = IDL.Record({
    'postCategory' : IDL.Text,
    'division' : IDL.Text,
    'circle' : IDL.Text,
    'state' : IDL.Text,
  });
  const Application = IDL.Record({
    'id' : ApplicationId,
    'status' : ApplicationStatus,
    'documentUrls' : IDL.Vec(IDL.Text),
    'paymentStatus' : PaymentStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'submittedAt' : IDL.Opt(Timestamp),
    'educationDetails' : EducationDetails,
    'preferences' : Preferences,
  });
  const PaymentId = IDL.Nat;
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'netbanking' : IDL.Null,
    'card' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : PaymentId,
    'status' : PaymentStatus,
    'method' : PaymentMethod,
    'applicationId' : ApplicationId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'applicant' : IDL.Null, 'admin' : IDL.Null });
  const AddressType = IDL.Record({
    'street' : IDL.Text,
    'doorNo' : IDL.Text,
    'city' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : UserId,
    'dob' : IDL.Text,
    'principal' : IDL.Principal,
    'subcategory' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'photoUrl' : IDL.Opt(IDL.Text),
    'aadhaar' : IDL.Text,
    'email' : IDL.Text,
    'isVerified' : IDL.Bool,
    'signatureUrl' : IDL.Opt(IDL.Text),
    'address' : AddressType,
    'gender' : IDL.Text,
    'category' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const CandidateLoginResult = IDL.Record({
    'status' : AdminCandidateStatus,
    'token' : IDL.Text,
    'name' : IDL.Text,
    'mobile' : IDL.Text,
    'registrationNo' : IDL.Text,
  });
  const ShortlistedCandidate = IDL.Record({
    'id' : CandidateId,
    'applicationId' : ApplicationId,
    'rank' : IDL.Nat,
    'division' : IDL.Text,
    'circle' : IDL.Text,
    'state' : IDL.Text,
    'rollNumber' : IDL.Text,
    'category' : IDL.Text,
    'candidateName' : IDL.Text,
  });
  const Circle = IDL.Record({
    'id' : CircleId,
    'stateName' : IDL.Text,
    'divisions' : IDL.Vec(Division),
    'circleName' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpResponse = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    'addDocumentUrl' : IDL.Func([ApplicationId, IDL.Text], [], []),
    'adminAddCandidate' : IDL.Func(
        [
          ApplicationId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [CandidateId],
        [],
      ),
    'adminAddDocument' : IDL.Func(
        [AdminCandidateId, IDL.Text, DocumentType, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Document, 'err' : IDL.Text })],
        [],
      ),
    'adminAddVacancy' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : Vacancy, 'err' : IDL.Text })],
        [],
      ),
    'adminCreateCircle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(Division)],
        [CircleId],
        [],
      ),
    'adminCreateNotification' : IDL.Func(
        [IDL.Text, IDL.Text, NotifType],
        [NotificationId],
        [],
      ),
    'adminCreateOfficialUpdate' : IDL.Func(
        [IDL.Text, IDL.Text, UpdateCategory, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : OfficialUpdate, 'err' : IDL.Text })],
        [],
      ),
    'adminDeactivateNotification' : IDL.Func([NotificationId], [], []),
    'adminDeleteCandidate' : IDL.Func([CandidateId], [], []),
    'adminDeleteCircle' : IDL.Func([CircleId], [], []),
    'adminDeleteDocument' : IDL.Func(
        [DocumentId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteNotification' : IDL.Func([NotificationId], [], []),
    'adminDeleteOfficialUpdate' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteUser' : IDL.Func([UserId], [], []),
    'adminDeleteVacancy' : IDL.Func(
        [VacancyId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetActiveVacancies' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Vacancy)],
        ['query'],
      ),
    'adminGetAllCandidates' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(AdminCandidateStatus)],
        [IDL.Vec(AdminCandidate)],
        ['query'],
      ),
    'adminGetAllVacancies' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Vacancy)],
        ['query'],
      ),
    'adminGetCandidate' : IDL.Func(
        [AdminCandidateId],
        [IDL.Opt(AdminCandidate)],
        ['query'],
      ),
    'adminGetCandidatesByRegistrationNo' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AdminCandidate)],
        ['query'],
      ),
    'adminGetDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'pending' : IDL.Nat,
            'approved' : IDL.Nat,
            'rejected' : IDL.Nat,
            'totalCandidates' : IDL.Nat,
            'circleStats' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'divisionStats' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          }),
        ],
        ['query'],
      ),
    'adminGetDocuments' : IDL.Func(
        [AdminCandidateId],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'adminListAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], []),
    'adminListAllOfficialUpdates' : IDL.Func([], [IDL.Vec(OfficialUpdate)], []),
    'adminListApplications' : IDL.Func([], [IDL.Vec(Application)], []),
    'adminListApplicationsByStatus' : IDL.Func(
        [ApplicationStatus],
        [IDL.Vec(Application)],
        [],
      ),
    'adminListPayments' : IDL.Func([], [IDL.Vec(Payment)], []),
    'adminListUsers' : IDL.Func([], [IDL.Vec(User)], []),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminRegisterCandidate' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          AddressInfo,
          AddressInfo,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ResultType,
          IDL.Vec(SubjectMark),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Vec(PostPreference),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : AdminCandidate, 'err' : IDL.Text })],
        [],
      ),
    'adminSetCandidateApplicationForm' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetUserRole' : IDL.Func([UserId, UserRole], [], []),
    'adminUpdateApplicationStatus' : IDL.Func(
        [ApplicationId, ApplicationStatus],
        [],
        [],
      ),
    'adminUpdateCandidateStatus' : IDL.Func(
        [AdminCandidateId, AdminCandidateStatus, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : AdminCandidate, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateCircle' : IDL.Func(
        [CircleId, IDL.Text, IDL.Text, IDL.Vec(Division)],
        [],
        [],
      ),
    'adminUpdateFeeStatus' : IDL.Func(
        [AdminCandidateId, FeeStatus],
        [IDL.Variant({ 'ok' : AdminCandidate, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateNotification' : IDL.Func(
        [NotificationId, IDL.Text, IDL.Text, NotifType],
        [],
        [],
      ),
    'adminUpdateOfficialUpdate' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Variant({ 'ok' : OfficialUpdate, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdatePaymentStatus' : IDL.Func([PaymentId, PaymentStatus], [], []),
    'adminUpdateVacancy' : IDL.Func(
        [VacancyId, IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : Vacancy, 'err' : IDL.Text })],
        [],
      ),
    'adminVerifyUser' : IDL.Func([UserId], [], []),
    'candidateLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : CandidateLoginResult, 'err' : IDL.Text })],
        [],
      ),
    'chatWithAI' : IDL.Func([IDL.Text], [IDL.Text], []),
    'confirmPayment' : IDL.Func([PaymentId, IDL.Text], [], []),
    'createApplication' : IDL.Func(
        [EducationDetails, Preferences],
        [ApplicationId],
        [],
      ),
    'getApplicationById' : IDL.Func(
        [ApplicationId],
        [IDL.Opt(Application)],
        ['query'],
      ),
    'getCandidateByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getCandidateById' : IDL.Func(
        [CandidateId],
        [IDL.Opt(ShortlistedCandidate)],
        ['query'],
      ),
    'getCandidateProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AdminCandidate)],
        ['query'],
      ),
    'getCircleById' : IDL.Func([CircleId], [IDL.Opt(Circle)], ['query']),
    'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getNotificationById' : IDL.Func(
        [NotificationId],
        [IDL.Opt(Notification)],
        ['query'],
      ),
    'getPaymentById' : IDL.Func([PaymentId], [IDL.Opt(Payment)], ['query']),
    'getUserById' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'httpTransform' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : HttpResponse,
          }),
        ],
        [HttpResponse],
        ['query'],
      ),
    'initiatePayment' : IDL.Func(
        [ApplicationId, IDL.Nat, PaymentMethod],
        [PaymentId],
        [],
      ),
    'listActiveNotifications' : IDL.Func(
        [],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'listActiveOfficialUpdates' : IDL.Func(
        [],
        [IDL.Vec(OfficialUpdate)],
        ['query'],
      ),
    'listAllCandidates' : IDL.Func(
        [],
        [IDL.Vec(ShortlistedCandidate)],
        ['query'],
      ),
    'listAllCircles' : IDL.Func([], [IDL.Vec(Circle)], ['query']),
    'listCandidatesByCircle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ShortlistedCandidate)],
        ['query'],
      ),
    'listCandidatesByState' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ShortlistedCandidate)],
        ['query'],
      ),
    'listCirclesByState' : IDL.Func([IDL.Text], [IDL.Vec(Circle)], ['query']),
    'listOfficialUpdatesByCategory' : IDL.Func(
        [UpdateCategory],
        [IDL.Vec(OfficialUpdate)],
        ['query'],
      ),
    'listStates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'registerUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          AddressType,
        ],
        [UserId],
        [],
      ),
    'requestOTP' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'submitApplication' : IDL.Func([ApplicationId], [], []),
    'updateApplication' : IDL.Func(
        [ApplicationId, EducationDetails, Preferences],
        [],
        [],
      ),
    'updatePhotoUrl' : IDL.Func([IDL.Text], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, AddressType],
        [],
        [],
      ),
    'updateSignatureUrl' : IDL.Func([IDL.Text], [], []),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };