/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddressInfo {
  'street' : string,
  'doorNo' : string,
  'district' : string,
  'state' : string,
  'village' : string,
  'pincode' : string,
}
export interface AddressType {
  'street' : string,
  'doorNo' : string,
  'city' : string,
  'district' : string,
  'state' : string,
  'pincode' : string,
}
export interface AdminCandidate {
  'id' : AdminCandidateId,
  'ph' : boolean,
  'dob' : string,
  'subjectMarks' : Array<SubjectMark>,
  'isEmployed' : boolean,
  'status' : AdminCandidateStatus,
  'divisionForVerification' : string,
  'photoPath' : string,
  'postPreferences' : Array<PostPreference>,
  'percentageObtained' : string,
  'canRideBicycle' : boolean,
  'feeStatus' : FeeStatus,
  'name' : string,
  'createdAt' : bigint,
  'rejectionReason' : string,
  'division' : string,
  'circle' : string,
  'totalCgpa' : string,
  'aadhaar' : string,
  'declarationsAccepted' : boolean,
  'email' : string,
  'permanentAddress' : AddressInfo,
  'updatedAt' : bigint,
  'yearOfPassing' : string,
  'signaturePath' : string,
  'fatherName' : string,
  'nocAvailable' : boolean,
  'gender' : string,
  'totalGrade' : string,
  'boardName' : string,
  'category' : string,
  'resultType' : ResultType,
  'mobile' : string,
  'registrationNo' : string,
  'stateOfBoard' : string,
  'boardRemarks' : string,
  'presentAddress' : AddressInfo,
  'applicationFormData' : [] | [string],
}
export type AdminCandidateId = bigint;
export type AdminCandidateStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Verified' : null } |
  { 'Pending' : null };
export interface Application {
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'documentUrls' : Array<string>,
  'paymentStatus' : PaymentStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'submittedAt' : [] | [Timestamp],
  'educationDetails' : EducationDetails,
  'preferences' : Preferences,
}
export type ApplicationId = bigint;
export type ApplicationStatus = { 'submitted' : null } |
  { 'underReview' : null } |
  { 'rejected' : null } |
  { 'shortlisted' : null } |
  { 'draft' : null };
export type CandidateId = bigint;
export interface CandidateLoginResult {
  'status' : AdminCandidateStatus,
  'token' : string,
  'name' : string,
  'mobile' : string,
  'registrationNo' : string,
}
export interface Circle {
  'id' : CircleId,
  'stateName' : string,
  'divisions' : Array<Division>,
  'circleName' : string,
}
export type CircleId = bigint;
export interface Division {
  'id' : bigint,
  'name' : string,
  'posts' : Array<Post>,
}
export interface Document {
  'id' : DocumentId,
  'documentType' : DocumentType,
  'fileName' : string,
  'registrationNo' : string,
  'candidateId' : AdminCandidateId,
  'uploadedAt' : bigint,
  'fileKey' : string,
}
export type DocumentId = bigint;
export type DocumentType = { 'TenthCertificate' : null } |
  { 'Aadhaar' : null } |
  { 'TwelfthCertificate' : null } |
  { 'CharacterCertificate' : null } |
  { 'PanCard' : null } |
  { 'ComputerCertificate' : null } |
  { 'Photo' : null } |
  { 'AttestationForm' : null } |
  { 'Domicile' : null } |
  { 'MedicalCertificate' : null } |
  { 'CasteCertificate' : null } |
  { 'IncomeCertificate' : null } |
  { 'Signature' : null } |
  { 'RegistrationForm' : null } |
  { 'IdentityCertificate' : null };
export interface EducationDetails {
  'totalMarks' : bigint,
  'marksObtained' : bigint,
  'yearOfPassing' : string,
  'boardName' : string,
  'percentage' : number,
}
export type FeeStatus = { 'Failed' : null } |
  { 'Paid' : null } |
  { 'Pending' : null };
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpResponse {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type NotifType = { 'important' : null } |
  { 'urgent' : null } |
  { 'general' : null };
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'content' : string,
  'notifType' : NotifType,
  'date' : Timestamp,
  'createdBy' : UserId,
  'isActive' : boolean,
}
export type NotificationId = bigint;
export interface OfficialUpdate {
  'id' : string,
  'title' : string,
  'content' : string,
  'date' : Timestamp,
  'createdBy' : string,
  'isActive' : boolean,
  'pdfUrl' : [] | [string],
  'category' : UpdateCategory,
  'isNew' : boolean,
}
export interface Payment {
  'id' : PaymentId,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'applicationId' : ApplicationId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'amount' : bigint,
  'transactionId' : string,
}
export type PaymentId = bigint;
export type PaymentMethod = { 'upi' : null } |
  { 'netbanking' : null } |
  { 'card' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'success' : null } |
  { 'notRequired' : null } |
  { 'failed' : null };
export interface Post {
  'stPosts' : bigint,
  'scPosts' : bigint,
  'obcPosts' : bigint,
  'category' : string,
  'totalPosts' : bigint,
  'urPosts' : bigint,
}
export interface PostPreference {
  'postType' : string,
  'preferenceNo' : bigint,
  'branchOfficeName' : string,
  'basicPay' : bigint,
  'category' : string,
}
export interface Preferences {
  'postCategory' : string,
  'division' : string,
  'circle' : string,
  'state' : string,
}
export type ResultType = { 'CGPA' : null } |
  { 'Percentage' : null } |
  { 'GradePoint' : null };
export interface ShortlistedCandidate {
  'id' : CandidateId,
  'applicationId' : ApplicationId,
  'rank' : bigint,
  'division' : string,
  'circle' : string,
  'state' : string,
  'rollNumber' : string,
  'category' : string,
  'candidateName' : string,
}
export interface SubjectMark { 'subject' : string, 'marksOrGrade' : string }
export type Timestamp = bigint;
export type UpdateCategory = { 'officialLetter' : null } |
  { 'recruitment' : null } |
  { 'tender' : null };
export interface User {
  'id' : UserId,
  'dob' : string,
  'principal' : Principal,
  'subcategory' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'photoUrl' : [] | [string],
  'aadhaar' : string,
  'email' : string,
  'isVerified' : boolean,
  'signatureUrl' : [] | [string],
  'address' : AddressType,
  'gender' : string,
  'category' : string,
  'mobile' : string,
}
export type UserId = bigint;
export type UserRole = { 'applicant' : null } |
  { 'admin' : null };
export interface Vacancy {
  'id' : VacancyId,
  'postType' : string,
  'branchOfficeName' : string,
  'createdAt' : bigint,
  'division' : string,
  'circle' : string,
  'basicPay' : bigint,
  'isActive' : boolean,
  'totalSeats' : bigint,
  'category' : string,
  'filledSeats' : bigint,
}
export type VacancyId = bigint;
export interface _SERVICE {
  'addDocumentUrl' : ActorMethod<[ApplicationId, string], undefined>,
  'adminAddCandidate' : ActorMethod<
    [ApplicationId, string, string, string, string, string, string, bigint],
    CandidateId
  >,
  'adminAddDocument' : ActorMethod<
    [AdminCandidateId, string, DocumentType, string, string],
    { 'ok' : Document } |
      { 'err' : string }
  >,
  'adminAddVacancy' : ActorMethod<
    [string, string, string, string, string, bigint, bigint],
    { 'ok' : Vacancy } |
      { 'err' : string }
  >,
  'adminCreateCircle' : ActorMethod<
    [string, string, Array<Division>],
    CircleId
  >,
  'adminCreateNotification' : ActorMethod<
    [string, string, NotifType],
    NotificationId
  >,
  'adminCreateOfficialUpdate' : ActorMethod<
    [string, string, UpdateCategory, [] | [string]],
    { 'ok' : OfficialUpdate } |
      { 'err' : string }
  >,
  'adminDeactivateNotification' : ActorMethod<[NotificationId], undefined>,
  'adminDeleteCandidate' : ActorMethod<[CandidateId], undefined>,
  'adminDeleteCircle' : ActorMethod<[CircleId], undefined>,
  'adminDeleteDocument' : ActorMethod<
    [DocumentId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteNotification' : ActorMethod<[NotificationId], undefined>,
  'adminDeleteOfficialUpdate' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteUser' : ActorMethod<[UserId], undefined>,
  'adminDeleteVacancy' : ActorMethod<
    [VacancyId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetActiveVacancies' : ActorMethod<[[] | [string]], Array<Vacancy>>,
  'adminGetAllCandidates' : ActorMethod<
    [[] | [string], [] | [string], [] | [AdminCandidateStatus]],
    Array<AdminCandidate>
  >,
  'adminGetAllVacancies' : ActorMethod<[[] | [string]], Array<Vacancy>>,
  'adminGetCandidate' : ActorMethod<[AdminCandidateId], [] | [AdminCandidate]>,
  'adminGetCandidatesByRegistrationNo' : ActorMethod<
    [string],
    Array<AdminCandidate>
  >,
  'adminGetDashboard' : ActorMethod<
    [],
    {
      'pending' : bigint,
      'approved' : bigint,
      'rejected' : bigint,
      'totalCandidates' : bigint,
      'circleStats' : Array<[string, bigint]>,
      'divisionStats' : Array<[string, bigint]>,
    }
  >,
  'adminGetDocuments' : ActorMethod<[AdminCandidateId], Array<Document>>,
  'adminListAllNotifications' : ActorMethod<[], Array<Notification>>,
  'adminListAllOfficialUpdates' : ActorMethod<[], Array<OfficialUpdate>>,
  'adminListApplications' : ActorMethod<[], Array<Application>>,
  'adminListApplicationsByStatus' : ActorMethod<
    [ApplicationStatus],
    Array<Application>
  >,
  'adminListPayments' : ActorMethod<[], Array<Payment>>,
  'adminListUsers' : ActorMethod<[], Array<User>>,
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminRegisterCandidate' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
      boolean,
      boolean,
      boolean,
      AddressInfo,
      AddressInfo,
      string,
      string,
      string,
      ResultType,
      Array<SubjectMark>,
      string,
      string,
      string,
      string,
      boolean,
      Array<PostPreference>,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
    ],
    { 'ok' : AdminCandidate } |
      { 'err' : string }
  >,
  'adminSetCandidateApplicationForm' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetUserRole' : ActorMethod<[UserId, UserRole], undefined>,
  'adminUpdateApplicationStatus' : ActorMethod<
    [ApplicationId, ApplicationStatus],
    undefined
  >,
  'adminUpdateCandidateStatus' : ActorMethod<
    [AdminCandidateId, AdminCandidateStatus, [] | [string]],
    { 'ok' : AdminCandidate } |
      { 'err' : string }
  >,
  'adminUpdateCircle' : ActorMethod<
    [CircleId, string, string, Array<Division>],
    undefined
  >,
  'adminUpdateFeeStatus' : ActorMethod<
    [AdminCandidateId, FeeStatus],
    { 'ok' : AdminCandidate } |
      { 'err' : string }
  >,
  'adminUpdateNotification' : ActorMethod<
    [NotificationId, string, string, NotifType],
    undefined
  >,
  'adminUpdateOfficialUpdate' : ActorMethod<
    [string, [] | [string], [] | [string], [] | [string], [] | [boolean]],
    { 'ok' : OfficialUpdate } |
      { 'err' : string }
  >,
  'adminUpdatePaymentStatus' : ActorMethod<
    [PaymentId, PaymentStatus],
    undefined
  >,
  'adminUpdateVacancy' : ActorMethod<
    [VacancyId, bigint, boolean],
    { 'ok' : Vacancy } |
      { 'err' : string }
  >,
  'adminVerifyUser' : ActorMethod<[UserId], undefined>,
  'candidateLogin' : ActorMethod<
    [string, string],
    { 'ok' : CandidateLoginResult } |
      { 'err' : string }
  >,
  'chatWithAI' : ActorMethod<[string], string>,
  'confirmPayment' : ActorMethod<[PaymentId, string], undefined>,
  'createApplication' : ActorMethod<
    [EducationDetails, Preferences],
    ApplicationId
  >,
  'getApplicationById' : ActorMethod<[ApplicationId], [] | [Application]>,
  'getCandidateByEmail' : ActorMethod<[string], [] | [string]>,
  'getCandidateById' : ActorMethod<[CandidateId], [] | [ShortlistedCandidate]>,
  'getCandidateProfile' : ActorMethod<[string], [] | [AdminCandidate]>,
  'getCircleById' : ActorMethod<[CircleId], [] | [Circle]>,
  'getMyApplications' : ActorMethod<[], Array<Application>>,
  'getMyPayments' : ActorMethod<[], Array<Payment>>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getNotificationById' : ActorMethod<[NotificationId], [] | [Notification]>,
  'getPaymentById' : ActorMethod<[PaymentId], [] | [Payment]>,
  'getUserById' : ActorMethod<[UserId], [] | [User]>,
  'httpTransform' : ActorMethod<
    [{ 'context' : Uint8Array, 'response' : HttpResponse }],
    HttpResponse
  >,
  'initiatePayment' : ActorMethod<
    [ApplicationId, bigint, PaymentMethod],
    PaymentId
  >,
  'listActiveNotifications' : ActorMethod<[], Array<Notification>>,
  'listActiveOfficialUpdates' : ActorMethod<[], Array<OfficialUpdate>>,
  'listAllCandidates' : ActorMethod<[], Array<ShortlistedCandidate>>,
  'listAllCircles' : ActorMethod<[], Array<Circle>>,
  'listCandidatesByCircle' : ActorMethod<[string], Array<ShortlistedCandidate>>,
  'listCandidatesByState' : ActorMethod<[string], Array<ShortlistedCandidate>>,
  'listCirclesByState' : ActorMethod<[string], Array<Circle>>,
  'listOfficialUpdatesByCategory' : ActorMethod<
    [UpdateCategory],
    Array<OfficialUpdate>
  >,
  'listStates' : ActorMethod<[], Array<string>>,
  'registerUser' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      AddressType,
    ],
    UserId
  >,
  'requestOTP' : ActorMethod<[string], boolean>,
  'submitApplication' : ActorMethod<[ApplicationId], undefined>,
  'updateApplication' : ActorMethod<
    [ApplicationId, EducationDetails, Preferences],
    undefined
  >,
  'updatePhotoUrl' : ActorMethod<[string], undefined>,
  'updateProfile' : ActorMethod<
    [string, string, string, string, string, AddressType],
    undefined
  >,
  'updateSignatureUrl' : ActorMethod<[string], undefined>,
  'verifyOTP' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];